#!/usr/bin/env python3
"""Validate and render a preview of a COLMAP-style text export.

This is a lightweight local importer for the handoff package generated by
``export_colmap_camera_poses.py``.  It does not require COLMAP to be installed:
it parses ``cameras.txt``, ``images.txt``, and ``points3D.txt`` directly,
reconstructs camera centers from qvec/tvec, and renders a top-down/side-view
diagnostic SVG.
"""

from __future__ import annotations

import argparse
import html
import json
import math
from pathlib import Path
from typing import Any


Vector3 = tuple[float, float, float]
Matrix3 = tuple[Vector3, Vector3, Vector3]


def data_lines(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    ]


def parse_cameras(path: Path) -> dict[int, dict[str, Any]]:
    cameras: dict[int, dict[str, Any]] = {}
    for line in data_lines(path):
        parts = line.split()
        if len(parts) < 5:
            raise ValueError(f"invalid camera line: {line}")
        camera_id = int(parts[0])
        cameras[camera_id] = {
            "camera_id": camera_id,
            "model": parts[1],
            "width": int(parts[2]),
            "height": int(parts[3]),
            "params": [float(value) for value in parts[4:]],
        }
    return cameras


def parse_images(path: Path) -> list[dict[str, Any]]:
    lines = data_lines(path)
    images: list[dict[str, Any]] = []
    # COLMAP images.txt has two data lines per image. The second line contains
    # POINTS2D and may be empty; after comment/empty filtering, our generated
    # model leaves only the pose lines.
    for line in lines:
        parts = line.split()
        if len(parts) < 10:
            continue
        image_id = int(parts[0])
        qvec = tuple(float(value) for value in parts[1:5])
        tvec = tuple(float(value) for value in parts[5:8])
        camera_id = int(parts[8])
        name = " ".join(parts[9:])
        images.append(
            {
                "image_id": image_id,
                "qvec": qvec,
                "tvec": tvec,
                "camera_id": camera_id,
                "name": name,
            }
        )
    return images


def parse_points(path: Path) -> list[dict[str, Any]]:
    points: list[dict[str, Any]] = []
    for line in data_lines(path):
        parts = line.split()
        if len(parts) < 8:
            raise ValueError(f"invalid points3D line: {line}")
        points.append(
            {
                "point3d_id": int(parts[0]),
                "xyz": (
                    float(parts[1]),
                    float(parts[2]),
                    float(parts[3]),
                ),
                "rgb": (
                    int(parts[4]),
                    int(parts[5]),
                    int(parts[6]),
                ),
                "error": float(parts[7]),
            }
        )
    return points


def qvec_to_rotation(qvec: tuple[float, float, float, float]) -> Matrix3:
    qw, qx, qy, qz = qvec
    return (
        (
            1.0 - 2.0 * qy * qy - 2.0 * qz * qz,
            2.0 * qx * qy - 2.0 * qz * qw,
            2.0 * qx * qz + 2.0 * qy * qw,
        ),
        (
            2.0 * qx * qy + 2.0 * qz * qw,
            1.0 - 2.0 * qx * qx - 2.0 * qz * qz,
            2.0 * qy * qz - 2.0 * qx * qw,
        ),
        (
            2.0 * qx * qz - 2.0 * qy * qw,
            2.0 * qy * qz + 2.0 * qx * qw,
            1.0 - 2.0 * qx * qx - 2.0 * qy * qy,
        ),
    )


def mat_transpose_vec_mul(matrix: Matrix3, vector: Vector3) -> Vector3:
    return (
        matrix[0][0] * vector[0] + matrix[1][0] * vector[1] + matrix[2][0] * vector[2],
        matrix[0][1] * vector[0] + matrix[1][1] * vector[1] + matrix[2][1] * vector[2],
        matrix[0][2] * vector[0] + matrix[1][2] * vector[1] + matrix[2][2] * vector[2],
    )


def camera_center_from_pose(qvec: tuple[float, float, float, float], tvec: Vector3) -> Vector3:
    # COLMAP stores world-to-camera transform: x_cam = R * x_world + t.
    # Therefore camera center in world coordinates is C = -R^T * t.
    rotation = qvec_to_rotation(qvec)
    rt_t = mat_transpose_vec_mul(rotation, tvec)
    return (-rt_t[0], -rt_t[1], -rt_t[2])


def camera_forward_from_pose(qvec: tuple[float, float, float, float]) -> Vector3:
    # Camera +z axis in world coordinates is R^T * [0, 0, 1], i.e. row 3 of R.
    rotation = qvec_to_rotation(qvec)
    return rotation[2]


def path_length(points: list[Vector3]) -> float:
    return sum(
        math.dist(first, second)
        for first, second in zip(points, points[1:])
    )


def bounds3(points: list[Vector3]) -> dict[str, float]:
    if not points:
        return {
            "x_min_m": 0.0,
            "x_max_m": 0.0,
            "y_min_m": 0.0,
            "y_max_m": 0.0,
            "z_min_m": 0.0,
            "z_max_m": 0.0,
        }
    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    zs = [point[2] for point in points]
    return {
        "x_min_m": min(xs),
        "x_max_m": max(xs),
        "y_min_m": min(ys),
        "y_max_m": max(ys),
        "z_min_m": min(zs),
        "z_max_m": max(zs),
    }


def rgb_hex(rgb: tuple[int, int, int]) -> str:
    return f"#{rgb[0]:02x}{rgb[1]:02x}{rgb[2]:02x}"


def render_svg(
    output: Path,
    export_dir: Path,
    cameras: dict[int, dict[str, Any]],
    images: list[dict[str, Any]],
    points: list[dict[str, Any]],
    validation: dict[str, Any],
) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    centers = [image["center_world_m"] for image in images]
    point_xyz = [point["xyz"] for point in points]
    all_top = [(point[0], point[1]) for point in centers]
    all_top.extend((point[0], point[1]) for point in point_xyz)
    if not all_top:
        all_top = [(0.0, 0.0)]
    xs = [point[0] for point in all_top]
    ys = [point[1] for point in all_top]
    min_x, max_x = min(xs) - 0.25, max(xs) + 0.25
    min_y, max_y = min(ys) - 0.25, max(ys) + 0.25

    side_origin = centers[0] if centers else (0.0, 0.0, 0.0)
    side_end = centers[-1] if centers else (1.0, 0.0, 0.0)
    axis_x = side_end[0] - side_origin[0]
    axis_y = side_end[1] - side_origin[1]
    axis_norm = math.hypot(axis_x, axis_y)
    if axis_norm < 1e-9:
        axis_x, axis_y, axis_norm = 1.0, 0.0, 1.0
    axis_x /= axis_norm
    axis_y /= axis_norm
    side_points = [
        (
            (point[0] - side_origin[0]) * axis_x + (point[1] - side_origin[1]) * axis_y,
            point[2],
        )
        for point in point_xyz
    ]
    side_centers = [
        (
            (center[0] - side_origin[0]) * axis_x + (center[1] - side_origin[1]) * axis_y,
            center[2],
        )
        for center in centers
    ]
    side_s_values = [value[0] for value in side_points + side_centers] or [0.0]
    side_z_values = [value[1] for value in side_points + side_centers] or [0.0]
    min_s, max_s = min(side_s_values) - 0.25, max(side_s_values) + 0.25
    min_z, max_z = min(side_z_values) - 0.10, max(side_z_values) + 0.10

    width, height = 1700, 1120
    top_left, top_top, top_right, top_bottom = 72, 144, 1040, 680
    side_left, side_top, side_right, side_bottom = 1110, 144, 1630, 680
    top_scale = min(
        (top_right - top_left) / max(max_x - min_x, 1e-9),
        (top_bottom - top_top) / max(max_y - min_y, 1e-9),
    )
    side_scale = min(
        (side_right - side_left) / max(max_s - min_s, 1e-9),
        (side_bottom - side_top) / max(max_z - min_z, 1e-9),
    )

    def tx(x_m: float) -> float:
        return top_left + (x_m - min_x) * top_scale

    def ty(y_m: float) -> float:
        return top_top + (max_y - y_m) * top_scale

    def sx(s_m: float) -> float:
        return side_left + (s_m - min_s) * side_scale

    def sz(z_m: float) -> float:
        return side_top + (max_z - z_m) * side_scale

    title = html.escape(export_dir.name)
    svg = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#07111f"/>',
        '<style>text { font-family: Inter, "Segoe UI", Arial, sans-serif; }</style>',
        f'<text x="48" y="52" fill="#f8fafc" font-size="30" font-weight="700">COLMAP export preview: {title}</text>',
        '<text x="48" y="84" fill="#94a3b8" font-size="16">Parsed cameras.txt, images.txt, and points3D.txt directly; no COLMAP executable required.</text>',
        '<text x="48" y="110" fill="#fbbf24" font-size="14">Preview validates handoff structure only; it does not run bundle adjustment or Gaussian splatting.</text>',
        f'<rect x="{top_left}" y="{top_top}" width="{top_right - top_left}" height="{top_bottom - top_top}" rx="18" fill="#0d1726" stroke="#334155"/>',
        f'<rect x="{side_left}" y="{side_top}" width="{side_right - side_left}" height="{side_bottom - side_top}" rx="18" fill="#0d1726" stroke="#334155"/>',
        f'<text x="{top_left}" y="{top_top - 18}" fill="#f8fafc" font-size="20" font-weight="700">Top-down x/y</text>',
        f'<text x="{side_left}" y="{side_top - 18}" fill="#f8fafc" font-size="20" font-weight="700">Side view along camera path</text>',
    ]

    for x_m in range(math.floor(min_x), math.ceil(max_x) + 1):
        x = tx(float(x_m))
        svg.append(f'<line x1="{x:.1f}" y1="{top_top}" x2="{x:.1f}" y2="{top_bottom}" stroke="#223246"/>')
        svg.append(f'<text x="{x + 4:.1f}" y="{top_bottom + 22}" fill="#64748b" font-size="12">{x_m}m</text>')
    for y_m in range(math.floor(min_y), math.ceil(max_y) + 1):
        y = ty(float(y_m))
        svg.append(f'<line x1="{top_left}" y1="{y:.1f}" x2="{top_right}" y2="{y:.1f}" stroke="#223246"/>')
        svg.append(f'<text x="{top_left - 42}" y="{y + 4:.1f}" fill="#64748b" font-size="12">{y_m}m</text>')

    for z_step in range(math.floor(min_z / 0.25), math.ceil(max_z / 0.25) + 1):
        z = z_step * 0.25
        y = sz(z)
        svg.append(f'<line x1="{side_left}" y1="{y:.1f}" x2="{side_right}" y2="{y:.1f}" stroke="#223246"/>')
        svg.append(f'<text x="{side_left - 60}" y="{y + 4:.1f}" fill="#64748b" font-size="12">{z:+.2f}m</text>')

    # Points first, cameras on top.
    for point in points:
        x_m, y_m, z_m = point["xyz"]
        color = rgb_hex(point["rgb"])
        opacity = 0.55 if point["error"] <= validation.get("median_point_error_px", 0.0) else 0.25
        svg.append(f'<circle cx="{tx(x_m):.1f}" cy="{ty(y_m):.1f}" r="2.1" fill="{color}" fill-opacity="{opacity:.2f}"/>')
    for point, (s_m, z_m) in zip(points, side_points):
        color = rgb_hex(point["rgb"])
        opacity = 0.55 if point["error"] <= validation.get("median_point_error_px", 0.0) else 0.25
        svg.append(f'<circle cx="{sx(s_m):.1f}" cy="{sz(z_m):.1f}" r="2.1" fill="{color}" fill-opacity="{opacity:.2f}"/>')

    if centers:
        path_data = " ".join(
            f'{"M" if index == 0 else "L"} {tx(center[0]):.1f} {ty(center[1]):.1f}'
            for index, center in enumerate(centers)
        )
        svg.append(f'<path d="{path_data}" fill="none" stroke="#f8fafc" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>')
    for image in images:
        center = image["center_world_m"]
        forward = image["forward_world"]
        arrow_len = 0.12
        svg.append(f'<circle cx="{tx(center[0]):.1f}" cy="{ty(center[1]):.1f}" r="9" fill="#f8fafc" stroke="#020617" stroke-width="2"/>')
        svg.append(
            f'<line x1="{tx(center[0]):.1f}" y1="{ty(center[1]):.1f}" '
            f'x2="{tx(center[0] + forward[0] * arrow_len):.1f}" y2="{ty(center[1] + forward[1] * arrow_len):.1f}" '
            'stroke="#38bdf8" stroke-width="3" stroke-linecap="round"/>'
        )
        svg.append(f'<text x="{tx(center[0]) + 12:.1f}" y="{ty(center[1]) - 8:.1f}" fill="#f8fafc" font-size="12" font-weight="700">{image["image_id"]}</text>')

    summary_y = 760
    camera = next(iter(cameras.values())) if cameras else {"model": "none", "width": 0, "height": 0}
    svg.extend(
        [
            f'<rect x="48" y="{summary_y - 36}" width="1604" height="128" rx="16" fill="#0d1726" stroke="#334155"/>',
            f'<text x="70" y="{summary_y}" fill="#f8fafc" font-size="18" font-weight="700">Validation passed: {str(validation["passed"]).lower()}; cameras: {len(cameras)}; images: {len(images)}; points: {len(points)}</text>',
            f'<text x="70" y="{summary_y + 30}" fill="#cbd5e1" font-size="15">Camera model: {html.escape(camera["model"])} {camera["width"]}x{camera["height"]}; path length: {validation["camera_path_length_m"]:.3f} m; median point error: {validation["median_point_error_px"]:.2f}px.</text>',
            f'<text x="70" y="{summary_y + 58}" fill="#94a3b8" font-size="14">Image files missing: {len(validation["missing_images"])}; quaternion norm range: {validation["min_quaternion_norm"]:.6f}..{validation["max_quaternion_norm"]:.6f}.</text>',
        ]
    )

    table_y = 930
    svg.append(f'<text x="48" y="{table_y - 34}" fill="#f8fafc" font-size="22" font-weight="700">Image pose records</text>')
    headers = ["id", "image", "center x", "center y", "center z"]
    columns = [54, 110, 430, 550, 670]
    for x, header in zip(columns, headers):
        svg.append(f'<text x="{x}" y="{table_y}" fill="#94a3b8" font-size="13" font-weight="700">{header}</text>')
    for row, image in enumerate(images[:10], start=1):
        y = table_y + row * 22
        center = image["center_world_m"]
        values = [
            image["image_id"],
            image["name"],
            f"{center[0]:+.3f}",
            f"{center[1]:+.3f}",
            f"{center[2]:+.3f}",
        ]
        for x, value in zip(columns, values):
            svg.append(f'<text x="{x}" y="{y}" fill="#cbd5e1" font-size="13">{html.escape(str(value))}</text>')

    svg.append("</svg>")
    output.write_text("\n".join(svg), encoding="utf-8")


def validate_export(
    export_dir: Path,
    cameras: dict[int, dict[str, Any]],
    images: list[dict[str, Any]],
    points: list[dict[str, Any]],
) -> dict[str, Any]:
    image_dir = export_dir / "images"
    missing_images = [
        image["name"]
        for image in images
        if not (image_dir / image["name"]).exists() or (image_dir / image["name"]).stat().st_size == 0
    ]
    q_norms = [math.sqrt(sum(value * value for value in image["qvec"])) for image in images]
    point_errors = [point["error"] for point in points]
    centers = [image["center_world_m"] for image in images]
    point_bounds = bounds3([point["xyz"] for point in points])
    center_bounds = bounds3(centers)
    passed = (
        len(cameras) >= 1
        and len(images) >= 2
        and not missing_images
        and all(abs(norm - 1.0) < 1e-6 for norm in q_norms)
    )
    return {
        "passed": passed,
        "camera_count": len(cameras),
        "image_count": len(images),
        "point_count": len(points),
        "missing_images": missing_images,
        "min_quaternion_norm": min(q_norms) if q_norms else 0.0,
        "max_quaternion_norm": max(q_norms) if q_norms else 0.0,
        "camera_path_length_m": path_length(centers),
        "median_point_error_px": sorted(point_errors)[len(point_errors) // 2] if point_errors else 0.0,
        "point_bounds": point_bounds,
        "camera_center_bounds": center_bounds,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate and preview a COLMAP-style text export"
    )
    parser.add_argument("export_dir", type=Path, help="Export directory containing images/ and sparse/0/")
    parser.add_argument("--output", type=Path, required=True, help="Output SVG preview")
    parser.add_argument("--json-output", type=Path, help="Optional validation JSON")
    args = parser.parse_args()

    export_dir = args.export_dir.resolve()
    sparse_dir = export_dir / "sparse" / "0"
    cameras = parse_cameras(sparse_dir / "cameras.txt")
    images = parse_images(sparse_dir / "images.txt")
    points = parse_points(sparse_dir / "points3D.txt")
    for image in images:
        center = camera_center_from_pose(image["qvec"], image["tvec"])
        image["center_world_m"] = center
        image["forward_world"] = camera_forward_from_pose(image["qvec"])
    validation = validate_export(export_dir, cameras, images, points)
    render_svg(args.output, export_dir, cameras, images, points, validation)

    payload = {
        "export_dir": str(export_dir),
        "validation": validation,
        "cameras": cameras,
        "images": images,
    }
    if args.json_output:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    print(f"Wrote {args.output}")
    if args.json_output:
        print(f"Wrote {args.json_output}")
    print(f"Validation passed: {validation['passed']}")
    print(f"Cameras/images/points: {len(cameras)}/{len(images)}/{len(points)}")
    print(f"Camera path length: {validation['camera_path_length_m']:.3f} m")
    print(f"Missing images: {len(validation['missing_images'])}")
    return 0 if validation["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
